import { StyleSheet } from 'react-native';

import { colors } from '@/shared/theme';

export const assistantChatSheetStyles = StyleSheet.create({
  sheet: {
    maxHeight: '86%',
    minHeight: 360,
    overflow: 'hidden',
    paddingBottom: 0,
    paddingHorizontal: 0,
  },
  header: {
    alignItems: 'center',
    borderBottomColor: colors.line,
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 11,
    marginBottom: 0,
    paddingBottom: 13,
    paddingHorizontal: 18,
    paddingTop: 14,
  },
  mark: {
    alignItems: 'center',
    backgroundColor: colors.deep,
    borderColor: colors.lime,
    borderRadius: 13,
    borderWidth: 1.5,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  headerCopy: { flex: 1, minWidth: 0 },
  title: { color: colors.ink, fontSize: 16, fontWeight: '800' },
  subtitle: { color: colors.sub, fontSize: 11, marginTop: 3 },
  list: {
    backgroundColor: colors.background,
    flexGrow: 1,
    flexShrink: 1,
  },
  listContent: {
    gap: 10,
    paddingBottom: 16,
    paddingHorizontal: 16,
    paddingTop: 14,
  },
  listContentEmpty: {
    flexGrow: 1,
    justifyContent: 'center',
  },
  empty: {
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingVertical: 28,
  },
  emptyTitle: { color: colors.deep, fontSize: 15, fontWeight: '800' },
  emptyHint: {
    color: colors.sub,
    fontSize: 12,
    lineHeight: 18,
    marginTop: 8,
    textAlign: 'center',
  },
  rowUser: { alignItems: 'flex-end' },
  bubbleUser: {
    backgroundColor: colors.deep,
    borderRadius: 16,
    borderBottomRightRadius: 4,
    maxWidth: '82%',
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  bubbleUserText: { color: colors.surface, fontSize: 14, lineHeight: 20 },
  rowAssistant: { alignItems: 'flex-start' },
  bubbleAssistant: {
    backgroundColor: colors.surface,
    borderColor: colors.line,
    borderRadius: 16,
    borderBottomLeftRadius: 4,
    borderWidth: 1,
    maxWidth: '88%',
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  bubbleAssistantText: { color: colors.ink, fontSize: 14, lineHeight: 20 },
  draftSlot: { width: '100%' },
  composer: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderTopColor: colors.line,
    borderTopWidth: 1,
    paddingTop: 12,
  },
});
