import { StyleSheet } from 'react-native';

import { colors } from '@/shared/theme';

export const mapPickerStyles = StyleSheet.create({
  screen: { backgroundColor: '#D8E4DE', flex: 1 },
  mapCanvas: { flex: 1 },
  mapError: {
    alignItems: 'center',
    backgroundColor: 'rgba(247, 248, 245, 0.96)',
    borderColor: colors.line,
    borderRadius: 16,
    borderWidth: 1,
    left: 44,
    paddingHorizontal: 20,
    paddingVertical: 18,
    position: 'absolute',
    right: 44,
    top: '38%',
    zIndex: 900,
  },
  mapErrorTitle: { color: colors.ink, fontSize: 14, fontWeight: '800', marginTop: 10 },
  mapErrorText: {
    color: colors.sub,
    fontSize: 11,
    lineHeight: 17,
    marginTop: 5,
    textAlign: 'center',
  },
  topArea: {
    left: 14,
    position: 'absolute',
    right: 14,
    top: 14,
    zIndex: 1000,
  },
  toolbar: { alignItems: 'center', flexDirection: 'row', gap: 8 },
  searchBox: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.line,
    borderRadius: 14,
    borderWidth: 1,
    elevation: 4,
    flex: 1,
    flexDirection: 'row',
    height: 48,
    paddingHorizontal: 12,
  },
  searchInput: {
    borderWidth: 0,
    color: colors.ink,
    flex: 1,
    fontSize: 13,
    height: 46,
    marginHorizontal: 8,
    outlineColor: 'transparent',
    outlineStyle: 'solid',
    outlineWidth: 0,
    paddingVertical: 0,
  },
  searchButton: {
    alignItems: 'center',
    height: 34,
    justifyContent: 'center',
    width: 30,
  },
  locateButton: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.line,
    borderRadius: 14,
    borderWidth: 1,
    elevation: 4,
    height: 48,
    justifyContent: 'center',
    width: 42,
  },
  locateButtonActive: { backgroundColor: colors.limeSoft },
  searchResults: {
    backgroundColor: colors.surface,
    borderColor: colors.line,
    borderRadius: 14,
    borderWidth: 1,
    marginLeft: 50,
    marginTop: 7,
    overflow: 'hidden',
  },
  searchResult: {
    alignItems: 'center',
    borderBottomColor: colors.line,
    borderBottomWidth: 1,
    flexDirection: 'row',
    minHeight: 48,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  searchResultLast: { borderBottomWidth: 0 },
  searchResultText: { color: colors.ink, flex: 1, fontSize: 12, lineHeight: 17, marginLeft: 9 },
  searchMessage: { color: colors.sub, fontSize: 11, padding: 14, textAlign: 'center' },
  locationError: {
    alignSelf: 'center',
    backgroundColor: 'rgba(247, 248, 245, 0.96)',
    borderColor: colors.line,
    borderRadius: 11,
    borderWidth: 1,
    marginTop: 7,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  locationErrorText: { color: colors.sub, fontSize: 11 },
  selectionCard: {
    backgroundColor: colors.surface,
    borderColor: colors.line,
    borderRadius: 18,
    borderWidth: 1,
    bottom: 16,
    elevation: 6,
    left: 14,
    padding: 14,
    position: 'absolute',
    right: 14,
    zIndex: 1000,
  },
  selectionHeading: { alignItems: 'center', flexDirection: 'row' },
  selectionIcon: {
    alignItems: 'center',
    backgroundColor: colors.limeSoft,
    borderRadius: 12,
    height: 38,
    justifyContent: 'center',
    marginRight: 10,
    width: 38,
  },
  selectionCopy: { flex: 1 },
  selectionKicker: { color: '#728456', fontSize: 10, fontWeight: '800' },
  selectionAddress: { color: colors.ink, fontSize: 13, lineHeight: 19, marginTop: 4 },
  selectionHint: { color: colors.sub, fontSize: 11, lineHeight: 17, marginTop: 4 },
  selectionMeta: { color: colors.muted, fontSize: 10, marginTop: 8 },
  confirmButton: {
    alignItems: 'center',
    backgroundColor: colors.deep,
    borderRadius: 12,
    height: 48,
    justifyContent: 'center',
    marginTop: 12,
  },
  confirmButtonDisabled: { opacity: 0.38 },
  confirmButtonText: { color: colors.surface, fontSize: 13, fontWeight: '800' },
});
