import { StyleSheet } from 'react-native';

import { colors } from '@/shared/theme';

export const detailStyles = StyleSheet.create({
  scheduleModalBackdrop: {
    alignItems: 'center',
    backgroundColor: 'rgba(20, 40, 33, 0.34)',
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  scheduleModalDismiss: {
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  scheduleModalSheet: {
    backgroundColor: '#F7F8F6',
    borderRadius: 24,
    maxHeight: '88%',
    maxWidth: 520,
    overflow: 'hidden',
    width: '100%',
  },
  scheduleModalReferenceHeader: {
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.94)',
    borderBottomColor: colors.line,
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 10,
    minHeight: 56,
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  scheduleModalHeaderCopy: { flex: 1, minWidth: 0 },
  scheduleModalHeaderTitle: {
    color: colors.ink,
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 18,
    marginTop: 2,
  },
  scheduleModalStatus: {
    alignItems: 'center',
    backgroundColor: '#EDF2DA',
    borderRadius: 8,
    flexDirection: 'row',
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  scheduleModalStatusText: { color: '#5C7045', fontSize: 8, fontWeight: '700' },
  scheduleModalStatusCompleted: { backgroundColor: '#E4EEE6' },
  scheduleModalStatusTextCompleted: { color: '#63866E' },
  scheduleModalScroll: { flexGrow: 0, flexShrink: 1 },
  scheduleModalScrollContent: { paddingBottom: 16, paddingHorizontal: 20, paddingTop: 18 },
  scheduleModalTitleBlock: {
    paddingBottom: 16,
    paddingRight: 2,
  },
  scheduleModalSource: { color: '#73806F', fontSize: 9, fontWeight: '600' },
  scheduleModalTitle: {
    color: colors.ink,
    fontSize: 22,
    fontWeight: '700',
    lineHeight: 29,
    marginTop: 7,
  },
  scheduleModalSubtitle: { color: '#7B877F', fontSize: 10, lineHeight: 15, marginTop: 7 },
  scheduleModalTimeCard: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderColor: '#DFE3DD',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    padding: 15,
  },
  scheduleModalTimeIcon: {
    alignItems: 'center',
    borderRadius: 10,
    flexShrink: 0,
    height: 35,
    justifyContent: 'center',
    width: 35,
  },
  scheduleModalTimeCopy: { flex: 1, minWidth: 0 },
  scheduleModalTimeEyebrow: { color: colors.sub, fontSize: 8 },
  scheduleModalDate: { color: colors.ink, fontSize: 13, fontWeight: '700', marginTop: 5 },
  scheduleModalTime: { color: '#64716A', fontSize: 11, marginTop: 4 },
  scheduleModalDuration: {
    backgroundColor: colors.deep,
    borderRadius: 8,
    color: colors.surface,
    flexShrink: 0,
    fontSize: 9,
    fontWeight: '700',
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  scheduleModalMeta: { borderTopColor: colors.line, borderTopWidth: 1, marginTop: 14 },
  scheduleModalMetaRow: {
    alignItems: 'center',
    borderBottomColor: colors.line,
    borderBottomWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 43,
  },
  scheduleModalMetaLabelGroup: { alignItems: 'center', flexDirection: 'row', gap: 7 },
  scheduleModalMetaLabel: { color: colors.sub, fontSize: 10 },
  scheduleModalMetaValue: { color: colors.ink, fontSize: 11, fontWeight: '600' },
  scheduleModalCompleted: { color: '#63866E' },
  scheduleModalActions: {
    backgroundColor: colors.surface,
    borderTopColor: colors.line,
    borderTopWidth: 1,
    flexDirection: 'row',
    gap: 9,
    minHeight: 66,
    paddingHorizontal: 20,
    paddingBottom: 12,
    paddingTop: 10,
  },
  scheduleModalSecondaryAction: {
    alignItems: 'center',
    backgroundColor: '#E9ECE8',
    borderRadius: 10,
    flex: 1,
    flexDirection: 'row',
    gap: 6,
    height: 44,
    justifyContent: 'center',
  },
  scheduleModalSecondaryText: { color: colors.ink, fontSize: 10, fontWeight: '700' },
  scheduleModalDeleteAction: {
    backgroundColor: colors.peach,
  },
  scheduleModalDeleteText: { color: colors.coral },
  scheduleModalDeleteDisabled: { opacity: 0.45 },
  scheduleModalPrimaryAction: {
    alignItems: 'center',
    backgroundColor: colors.deep,
    borderRadius: 10,
    flex: 1.35,
    flexDirection: 'row',
    gap: 6,
    height: 44,
    justifyContent: 'center',
  },
  scheduleModalPrimaryText: { color: colors.surface, fontSize: 10, fontWeight: '700' },
});
