import { StyleSheet } from 'react-native';

import { colors } from '@/shared/theme';

export const monthStyles = StyleSheet.create({
  monthContent: { paddingBottom: 28 },
  monthCard: {
    backgroundColor: colors.surface,
    borderColor: colors.line,
    borderRadius: 20,
    borderWidth: 1,
    marginBottom: 14,
    paddingHorizontal: 12,
    paddingVertical: 14,
  },
  monthHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 11,
    minHeight: 46,
    paddingHorizontal: 2,
  },
  monthNavButton: {
    alignItems: 'center',
    backgroundColor: '#EFEDE7',
    borderRadius: 9,
    height: 29,
    justifyContent: 'center',
    minWidth: 42,
    paddingHorizontal: 9,
  },
  monthNavText: { color: colors.sub, fontSize: 10, fontWeight: '700' },
  monthYear: { color: '#8C938F', fontSize: 6, textAlign: 'center' },
  monthTitle: {
    color: colors.ink,
    fontSize: 16,
    fontWeight: '700',
    marginTop: 2,
    textAlign: 'center',
  },
  weekdayRow: { flexDirection: 'row', gap: 3, height: 20, marginBottom: 0 },
  weekday: { color: colors.sub, flex: 1, fontSize: 10, paddingBottom: 6, textAlign: 'center' },
  monthGrid: { gap: 3 },
  monthWeekRow: { flexDirection: 'row', gap: 3 },
  monthDay: {
    alignItems: 'center',
    backgroundColor: '#EFEFEF',
    borderRadius: 10,
    flex: 1,
    height: 40,
    justifyContent: 'center',
  },
  monthDayActive: { backgroundColor: colors.deep },
  monthDaySelected: { backgroundColor: colors.limeSoft },
  monthDayMuted: { backgroundColor: 'rgba(239, 239, 239, 0.3)' },
  monthDayText: { color: colors.ink, fontSize: 12 },
  monthDayTextActive: { color: colors.surface, fontWeight: '800' },
  monthDayTextSelected: { color: colors.ink, fontWeight: '700' },
  monthDayTextMuted: { color: '#C2C6C3' },
  monthDot: {
    alignItems: 'center',
    backgroundColor: '#87A16C',
    borderRadius: 2,
    height: 4,
    justifyContent: 'center',
    marginTop: 3,
    width: 4,
  },
  monthDayActiveDot: { backgroundColor: colors.lime },
  monthCompletedMarker: {
    backgroundColor: '#7CA38A',
    borderRadius: 6,
    height: 12,
    marginTop: 2,
    width: 12,
  },
  monthSelectedHeading: {
    alignItems: 'center',
    borderBottomColor: colors.line,
    borderBottomWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
    marginTop: 0,
    minHeight: 35,
    paddingBottom: 6,
  },
  monthSelectedTitle: { color: colors.ink, fontSize: 16, fontWeight: '600' },
  scheduleEmpty: {
    backgroundColor: colors.surface,
    borderColor: colors.line,
    borderRadius: 14,
    borderStyle: 'dashed',
    borderWidth: 1,
    color: colors.sub,
    fontSize: 12,
    paddingHorizontal: 12,
    paddingVertical: 18,
    textAlign: 'center',
  },
});
