import { StyleSheet } from 'react-native';

import { colors } from '../constants/theme';

export const assistantStyles = StyleSheet.create({
  assistantScreen: { backgroundColor: colors.background, flex: 1, padding: 20 },
  assistantHeader: { paddingTop: 8 },
  assistantNavRow: {
    alignItems: 'center',
    flexDirection: 'row',
  },
  assistantEyebrow: {
    color: colors.muted,
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0,
    marginLeft: 11,
  },
  assistantTitle: { color: colors.ink, fontSize: 28, fontWeight: '800', marginTop: 18 },
  assistantSubtitle: { color: colors.sub, fontSize: 13, lineHeight: 20, marginTop: 8 },
  assistantMessageRow: { alignItems: 'flex-start', flexDirection: 'row', marginTop: 28 },
  assistantMark: {
    backgroundColor: colors.deep,
    borderColor: 'rgba(215,243,106,0.34)',
    borderRadius: 12,
    borderWidth: 1,
    elevation: 4,
    height: 38,
    alignItems: 'center',
    justifyContent: 'center',
    width: 38,
  },
  assistantBubble: {
    backgroundColor: colors.surface,
    borderColor: '#ECE9E2',
    borderRadius: 12,
    borderWidth: 1,
    flex: 1,
    marginLeft: 10,
    padding: 16,
  },
  assistantBubbleText: { color: colors.ink, fontSize: 14, lineHeight: 21 },
  assistantComposer: { flexShrink: 0, marginTop: 'auto' },
  selectedImageRow: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(20,40,33,0.09)',
    borderRadius: 12,
    borderWidth: 1,
    elevation: 2,
    flexDirection: 'row',
    marginBottom: 8,
    maxWidth: '78%',
    padding: 5,
  },
  selectedImageThumbnail: { borderRadius: 8, height: 34, width: 34 },
  selectedImageName: {
    color: colors.ink,
    flexShrink: 1,
    fontSize: 12,
    fontWeight: '600',
    marginHorizontal: 8,
  },
  selectedImageRemove: {
    alignItems: 'center',
    borderRadius: 9,
    height: 28,
    justifyContent: 'center',
    outlineColor: 'transparent',
    outlineStyle: 'solid',
    outlineWidth: 0,
    width: 28,
  },
  commandInputRow: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.96)',
    borderColor: 'rgba(20,40,33,0.09)',
    borderRadius: 18,
    borderWidth: 1,
    elevation: 4,
    flexDirection: 'row',
    gap: 5,
    minHeight: 60,
    padding: 8,
  },
  commandInputRowCompact: { gap: 3, paddingHorizontal: 6, paddingVertical: 7 },
  commandMedia: {
    alignItems: 'center',
    backgroundColor: '#F5F6F2',
    borderRadius: 14,
    height: 40,
    justifyContent: 'center',
    outlineColor: 'transparent',
    outlineStyle: 'solid',
    outlineWidth: 0,
    width: 40,
  },
  commandHold: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    flex: 1,
    height: 44,
    justifyContent: 'center',
    minWidth: 0,
    outlineColor: 'transparent',
    outlineStyle: 'solid',
    outlineWidth: 0,
  },
  commandHoldActive: {
    backgroundColor: colors.limeSoft,
    transform: [{ scale: 0.985 }],
  },
  commandHoldCompact: { height: 42 },
  commandHoldContent: {
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
  },
  commandHoldText: {
    color: '#1C2420',
    fontSize: 15,
    fontWeight: '700',
    letterSpacing: 0,
  },
  commandHoldTextCompact: { fontSize: 14 },
  commandWave: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 3,
    height: 24,
    left: 14,
    position: 'absolute',
  },
  commandWaveBar: {
    backgroundColor: '#142E26',
    borderRadius: 2,
    width: 3,
  },
  commandTextPanel: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: 5,
    minWidth: 0,
  },
  commandInput: {
    backgroundColor: '#F0F3EF',
    borderRadius: 12,
    borderWidth: 0,
    color: colors.ink,
    flex: 1,
    fontSize: 14,
    height: 44,
    minWidth: 0,
    outlineColor: 'transparent',
    outlineStyle: 'solid',
    outlineWidth: 0,
    paddingHorizontal: 13,
  },
  commandInputCompact: { height: 42 },
  commandInputFocused: {
    backgroundColor: '#FFFFFF',
    borderColor: '#AEBBB4',
    borderWidth: 1,
  },
  commandSend: {
    alignItems: 'center',
    backgroundColor: colors.deep,
    borderRadius: 12,
    height: 40,
    justifyContent: 'center',
    minWidth: 48,
    outlineColor: 'transparent',
    outlineStyle: 'solid',
    outlineWidth: 0,
    paddingHorizontal: 11,
  },
  commandSendCompact: { minWidth: 44, paddingHorizontal: 9 },
  commandSendText: { color: colors.surface, fontSize: 12, fontWeight: '700' },
  commandMode: {
    alignItems: 'center',
    backgroundColor: 'transparent',
    borderRadius: 14,
    height: 40,
    justifyContent: 'center',
    outlineColor: 'transparent',
    outlineStyle: 'solid',
    outlineWidth: 0,
    width: 40,
  },
  commandModeCompact: { height: 38, width: 36 },
  commandControlPressed: {
    backgroundColor: '#E7EBE4',
    transform: [{ scale: 0.94 }],
  },
  assistantDock: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,254,250,0.94)',
    borderTopColor: 'rgba(30,40,35,0.08)',
    borderTopWidth: 1,
    bottom: 0,
    height: 64,
    justifyContent: 'center',
    left: 0,
    paddingBottom: 8,
    position: 'absolute',
    right: 0,
    zIndex: 20,
  },
  assistantDockButton: {
    alignItems: 'center',
    backgroundColor: '#142821',
    borderRadius: 15,
    boxShadow: '0 7px 18px rgba(20,40,33,0.25)',
    elevation: 6,
    height: 46,
    justifyContent: 'center',
    width: 46,
  },
  assistantDockButtonPressed: { opacity: 0.9, transform: [{ scale: 0.95 }] },
});
