import { StyleSheet } from 'react-native';

import { colors } from '@/shared/theme';

export const createSheetStyles = StyleSheet.create({
  modalBackdrop: {
    alignItems: 'center',
    backgroundColor: 'rgba(22,32,28,0.52)',
    flex: 1,
    justifyContent: 'flex-end',
  },
  modalDismiss: { alignSelf: 'stretch', flex: 1 },
  modalKeyboardAvoider: { flex: 1 },
  editModalBackdrop: {
    alignItems: 'center',
    backgroundColor: 'rgba(22,32,28,0.52)',
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 18,
  },
  editModalDismiss: { bottom: 0, left: 0, position: 'absolute', right: 0, top: 0 },
  standardSheet: {
    backgroundColor: colors.surface,
    borderTopLeftRadius: 26,
    borderTopRightRadius: 26,
    padding: 18,
    paddingBottom: 28,
    maxWidth: 430,
    maxHeight: '92%',
    width: '100%',
  },
  standardDialog: {
    borderRadius: 20,
    maxHeight: '88%',
    paddingBottom: 20,
    paddingTop: 20,
  },
  sheetCloseText: { color: colors.ink, fontSize: 17 },
  fieldLabel: { color: colors.ink, fontSize: 11, fontWeight: '700', marginBottom: 7, marginTop: 9 },
  formInputControl: {
    borderColor: colors.line,
    borderRadius: 10,
    borderWidth: 1,
    color: colors.ink,
    fontSize: 13,
    height: 48,
    paddingHorizontal: 13,
  },
  formInputMultiline: {
    height: 72,
    paddingTop: 12,
    textAlignVertical: 'top',
  },
  pickerField: {
    alignItems: 'center',
    borderColor: colors.line,
    borderRadius: 10,
    borderWidth: 1,
    flexDirection: 'row',
    height: 48,
    paddingHorizontal: 13,
  },
  pickerFieldText: { color: colors.ink, flex: 1, fontSize: 13, fontWeight: '600' },
  pickerFieldPlaceholder: { color: colors.muted, fontWeight: '500' },
  formError: { color: '#B66752', fontSize: 11, marginTop: 10 },
  moreToggle: {
    alignItems: 'center',
    backgroundColor: colors.surfaceTint,
    borderRadius: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 14,
    minHeight: 44,
    paddingHorizontal: 12,
  },
  moreToggleActive: { backgroundColor: colors.limeSoft },
  moreToggleText: { color: '#7D8982', fontSize: 13, fontWeight: '800' },
  moreToggleTextActive: { color: '#52745D' },
  moreSection: { marginTop: 2 },
  fieldWithClear: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  fieldWithClearMain: {
    flex: 1,
    minWidth: 0,
  },
  locationField: {
    alignItems: 'center',
    borderColor: colors.line,
    borderRadius: 10,
    borderWidth: 1,
    flexDirection: 'row',
    minHeight: 52,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  locationFieldMain: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
  },
  locationFieldIcon: {
    alignItems: 'center',
    backgroundColor: colors.limeSoft,
    borderRadius: 9,
    height: 32,
    justifyContent: 'center',
    width: 32,
  },
  locationFieldCopy: { flex: 1, marginLeft: 10 },
  locationFieldTitle: { color: colors.ink, fontSize: 13, fontWeight: '700' },
  locationFieldPlaceholder: { color: colors.muted, fontWeight: '500' },
  locationFieldHint: { color: colors.sub, fontSize: 10, marginTop: 2 },
  locationClear: {
    backgroundColor: colors.surfaceTint,
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  locationClearText: { color: colors.sub, fontSize: 11, fontWeight: '700' },
  standardPrimary: {
    alignItems: 'center',
    backgroundColor: colors.deep,
    borderRadius: 12,
    justifyContent: 'center',
    marginTop: 14,
    minHeight: 50,
  },
  standardPrimaryText: { color: colors.surface, fontSize: 14, fontWeight: '800' },
  standardFormScroll: { flexGrow: 0, flexShrink: 1 },
  standardFormContent: { paddingBottom: 2 },
  sheetHandle: {
    alignSelf: 'center',
    backgroundColor: '#D8D6CF',
    borderRadius: 3,
    height: 4,
    marginBottom: 18,
    width: 34,
  },
  sheetHeader: {
    alignItems: 'flex-end',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  sheetEyebrow: {
    color: colors.muted,
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0,
    marginBottom: 6,
  },
  sheetTitle: { color: colors.ink, fontSize: 23, fontWeight: '800' },
  sheetClose: {
    alignItems: 'center',
    backgroundColor: colors.surfaceTint,
    borderRadius: 11,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
});
